before_commands:
    - "composer update --prefer-source"

filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_analyzer:
      filter:
        paths: ["src/*", "tests/*"]
    php_cs_fixer: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
