before_commands:
    - "composer update --prefer-source"

filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
