filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
tools:
    php_sim: true
    php_pdepend: false
    php_analyzer: true
    php_cs_fixer: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
