filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        remove_extra_empty_lines: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        newline_at_end_of_file: true
        avoid_fixme_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        avoid_todo_comments: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        classes_in_camel_caps: true
        encourage_postdec_operator: true
        fix_line_ending: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        function_in_camel_caps: true
        line_length:
            max_length: '120'
        instanceof_class_exists: true
        function_in_camel_caps: true
        foreach_usable_as_reference: true
        foreach_traversable: true
        fix_line_ending: true
        fix_doc_comments: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        comparison_always_same_result: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        classes_in_camel_caps: true
        catch_class_exists: true
        call_to_parent_method: true
        blank_line_after_namespace_declaration: true
        avoid_useless_overridden_methods: true
        avoid_usage_of_logical_operators: true
        avoid_todo_comments: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_fixme_comments: true
        avoid_entity_manager_injection: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        assignment_of_null_return: true
        argument_type_checks: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: false
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
                always: true
                else_on_new_line: false
            for:
                opening: undefined
                always: true
            while:
                opening: undefined
                always: true
            do_while:
                opening: undefined
                always: true
                while_on_new_line: false
            switch:
                opening: undefined
            try:
                opening: undefined
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
